In [2]:
import numpy as np
a=np.array([[1,2,3,4],[11,23,33,40],[5,7,9,90]])
print(a)

[[ 1  2  3  4]
 [11 23 33 40]
 [ 5  7  9 90]]


In [3]:
a[0,0]


1

In [4]:
a[2,3]


90

In [5]:
a[1,2]


33

In [7]:
a.shape


(3, 4)

In [8]:
a[2,1:3]


array([7, 9])

In [13]:
a[1:3,2:4]



array([[33, 40],
       [ 9, 90]])

In [14]:
a[1:,2:]

array([[33, 40],
       [ 9, 90]])

In [15]:
a[0:3]

array([[ 1,  2,  3,  4],
       [11, 23, 33, 40],
       [ 5,  7,  9, 90]])

In [16]:
a[1,:2]

array([11, 23])

#arange


In [17]:
a[0:3,3:]


array([[ 4],
       [40],
       [90]])

In [18]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Reshape

In [19]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.sqrt(81)

9.0

In [21]:
a.max()

90

In [22]:
a.min()


1

In [26]:
a.argmin()

0

In [27]:
a.argmax()

11

In [28]:
a.argmin()

0

In [29]:
a*2

array([[  2,   4,   6,   8],
       [ 22,  46,  66,  80],
       [ 10,  14,  18, 180]])

In [30]:
a+10

array([[ 11,  12,  13,  14],
       [ 21,  33,  43,  50],
       [ 15,  17,  19, 100]])

# Random

In [31]:
np.random.rand(2,2)

array([[0.47435121, 0.10962062],
       [0.2957289 , 0.00197306]])

In [32]:
np.random.rand(2)

array([0.17359452, 0.17828457])

In [34]:
np.random.randint(9,90,12)

array([38, 34, 62, 14, 35, 17, 79, 38, 17, 81, 36, 66])

In [36]:
np.random.randint(9,90,12).reshape(6,2)

array([[71, 38],
       [10, 21],
       [13, 40],
       [50, 42],
       [39, 80],
       [86, 72]])

In [38]:
s=np.random.randint(9,90,12).reshape(6,2)

In [39]:
s

array([[25, 44],
       [32, 24],
       [25, 64],
       [30, 30],
       [33, 40],
       [16, 47]])

In [40]:
s.sum()

410

In [41]:
s.sum(axis=1)

array([69, 56, 89, 60, 73, 63])

In [42]:
s.sum(axis=0)

array([161, 249])

# 3D

In [43]:
b=np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,40],[6,60]]])

In [44]:
b

[[[4, 40], [5, 50], [6, 60]],
 [[7, 70], [8, 80], [9, 90]],
 [[5, 55], [4, 40], [6, 60]]]

In [46]:
b.shape


AttributeError: 'list' object has no attribute 'shape'

In [47]:
b

[[[4, 40], [5, 50], [6, 60]],
 [[7, 70], [8, 80], [9, 90]],
 [[5, 55], [4, 40], [6, 60]]]

In [48]:
b.shape()

AttributeError: 'list' object has no attribute 'shape'

In [50]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [51]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

In [52]:
b

[[[4, 40], [5, 50], [6, 60]],
 [[7, 70], [8, 80], [9, 90]],
 [[5, 55], [4, 40], [6, 60]]]

In [54]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

# Nan -not a number

In [55]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [56]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [58]:
x.dtype

dtype('float64')