In [1]:
import numpy as np
a=np.array([[1,2,3,4],[11,23,33,40],[5,7,9,90]])
print(a)

[[ 1  2  3  4]
 [11 23 33 40]
 [ 5  7  9 90]]


In [2]:
a[0,0]


1

In [3]:
a[2,3]


90

In [4]:
a[1,2]


33

In [5]:
a.shape


(3, 4)

In [6]:
a[2,1:3]


array([7, 9])

In [7]:
a[1:3,2:4]



array([[33, 40],
       [ 9, 90]])

In [8]:
a[1:,2:]

array([[33, 40],
       [ 9, 90]])

In [9]:
a[0:3]

array([[ 1,  2,  3,  4],
       [11, 23, 33, 40],
       [ 5,  7,  9, 90]])

In [10]:
a[1,:2]

array([11, 23])

#arange


In [11]:
a[0:3,3:]


array([[ 4],
       [40],
       [90]])

In [12]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Reshape

In [13]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np.sqrt(81)

9.0

In [15]:
a.max()

90

In [16]:
a.min()


1

In [17]:
a.argmin()

0

In [18]:
a.argmax()

11

In [19]:
a.argmin()

0

In [20]:
a*2

array([[  2,   4,   6,   8],
       [ 22,  46,  66,  80],
       [ 10,  14,  18, 180]])

In [21]:
a+10

array([[ 11,  12,  13,  14],
       [ 21,  33,  43,  50],
       [ 15,  17,  19, 100]])

# Random

In [22]:
np.random.rand(2,2)

array([[0.16773   , 0.44591831],
       [0.92619596, 0.87264386]])

In [23]:
np.random.rand(2)

array([0.59048221, 0.87128174])

In [24]:
np.random.randint(9,90,12)

array([83, 48, 37, 23, 37, 74, 77, 62, 17, 86, 11, 77])

In [25]:
np.random.randint(9,90,12).reshape(6,2)

array([[56, 38],
       [75, 20],
       [25, 30],
       [25, 61],
       [87, 73],
       [89, 81]])

In [26]:
s=np.random.randint(9,90,12).reshape(6,2)

In [27]:
s

array([[67, 54],
       [22, 76],
       [ 9, 38],
       [88, 29],
       [38, 78],
       [48, 65]])

In [28]:
s.sum()

612

In [29]:
s.sum(axis=1)

array([121,  98,  47, 117, 116, 113])

In [30]:
s.sum(axis=0)

array([272, 340])

# 3D

In [31]:
b=np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,40],[6,60]]])

In [32]:
b

array([[[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 5, 55],
        [ 4, 40],
        [ 6, 60]]])

In [33]:
b.shape


(3, 3, 2)

In [34]:
b

array([[[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 5, 55],
        [ 4, 40],
        [ 6, 60]]])

In [35]:
b.shape()

TypeError: 'tuple' object is not callable

In [36]:
b.shape

(3, 3, 2)

In [37]:
b.shape

(3, 3, 2)

In [38]:
b

array([[[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 5, 55],
        [ 4, 40],
        [ 6, 60]]])

In [39]:
b.shape

(3, 3, 2)

# Nan -not a number

In [40]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [41]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [42]:
x.dtype

dtype('float64')